import function
import loadSaveExit
import ubahPassword
import ubahtipejin
import help
import hapusjin
import hancurkancandi
import ayamberkokok
import laporancandi
import laporanjin
import login
import bangun
import kumpul
import batch_bangun
import batch_kumpul
import summonjin